{
  "hash": "cadc58732594e076888e2b062f73f881",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Weird Dads\"\nauthor: \"Nikhita Purohit\"\ndate: \"2025-11-04\"\ncategories: [code]\n---\n\n\n\n# ![](images/clipboard-2484901654.png)\n\n# Is your dad weird?\n\nAsking SMI and MIT Students If They Think Their Dad is Weird\n\nEXPERIMENT OBJECTIVE: To find out if SMI dads are weirder than MIT dads.\n\n## *1. Setting up R Packages*\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# SETUP CHUNK- LIBRARIES\n#| label: setup\n#| echo: false\n#| warning: false\n#| message: false\n\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.2\n✔ ggplot2   4.0.0     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.1.0     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(mosaic) # Our all-in-one package\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\nAttaching package: 'mosaic'\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(skimr) # Looking at data\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'skimr'\n\nThe following object is masked from 'package:mosaic':\n\n    n_missing\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(janitor) # Clean the data\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'janitor'\n\nThe following objects are masked from 'package:stats':\n\n    chisq.test, fisher.test\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(naniar) # Handle missing data\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'naniar'\n\nThe following object is masked from 'package:skimr':\n\n    n_complete\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(visdat) # Visualise missing data\nlibrary(tinytable) # Printing Static Tables for our data\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'tinytable'\n\nThe following object is masked from 'package:ggplot2':\n\n    theme_void\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(DT) # Interactive Tables for our data\nlibrary(crosstable) # Multiple variable summaries\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'crosstable'\n\nThe following object is masked from 'package:purrr':\n\n    compact\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(vcd)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: grid\n\nAttaching package: 'vcd'\n\nThe following object is masked from 'package:mosaic':\n\n    mplot\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(visStatistics) # One package to test them all\n### Dataset from Chihara and Hesterberg's book (Second Edition)\nlibrary(resampledata)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'resampledata'\n\nThe following object is masked from 'package:datasets':\n\n    Titanic\n```\n\n\n:::\n:::\n\n\n\n## 2. *Read Data*\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_modified <- dad <- readr::read_csv(\"../data/3-weird_dads.csv\")%>%\n  # Clean variable names\n  janitor::clean_names(case=\"snake\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 65 Columns: 4\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (4): gender, college, is_dad_weird, name\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\ndad_modified\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 65 × 4\n   gender college is_dad_weird name   \n   <chr>  <chr>   <chr>        <chr>  \n 1 F      SMI     No           Manya  \n 2 F      SMI     No           Sradha \n 3 M      SMI     No           Arun   \n 4 F      SMI     Yes          Nidhi  \n 5 M      MIT     No           Shaurya\n 6 M      MIT     No           Pratham\n 7 M      MIT     No           Jeevan \n 8 M      SMI     No           Dhruv  \n 9 F      SMI     Yes          Aakrati\n10 M      SMI     Yes          Aakrsh \n# ℹ 55 more rows\n```\n\n\n:::\n:::\n\n\n\n## 3. *Examine Data*\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndplyr::glimpse(dad_modified)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 65\nColumns: 4\n$ gender       <chr> \"F\", \"F\", \"M\", \"F\", \"M\", \"M\", \"M\", \"M\", \"F\", \"M\", \"F\", \"M…\n$ college      <chr> \"SMI\", \"SMI\", \"SMI\", \"SMI\", \"MIT\", \"MIT\", \"MIT\", \"SMI\", \"…\n$ is_dad_weird <chr> \"No\", \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\", \"No\", \"Yes\", \"…\n$ name         <chr> \"Manya\", \"Sradha\", \"Arun\", \"Nidhi\", \"Shaurya\", \"Pratham\",…\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nskimr::skim(dad_modified)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |             |\n|:------------------------|:------------|\n|Name                     |dad_modified |\n|Number of rows           |65           |\n|Number of columns        |4            |\n|_______________________  |             |\n|Column type frequency:   |             |\n|character                |4            |\n|________________________ |             |\n|Group variables          |None         |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|gender        |         0|          1.00|   1|   2|     0|        3|          0|\n|college       |         0|          1.00|   3|   3|     0|        2|          0|\n|is_dad_weird  |         1|          0.98|   2|   3|     0|        2|          0|\n|name          |         0|          1.00|   4|  11|     0|       63|          0|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(dad_modified)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"gender\"       \"college\"      \"is_dad_weird\" \"name\"        \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nvisdat::vis_dat(dad, sort_type = TRUE, palette = \"default\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_modified <- dad %>% tidyr::drop_na()\ndad_modified\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 64 × 4\n   gender college is_dad_weird name   \n   <chr>  <chr>   <chr>        <chr>  \n 1 F      SMI     No           Manya  \n 2 F      SMI     No           Sradha \n 3 M      SMI     No           Arun   \n 4 F      SMI     Yes          Nidhi  \n 5 M      MIT     No           Shaurya\n 6 M      MIT     No           Pratham\n 7 M      MIT     No           Jeevan \n 8 M      SMI     No           Dhruv  \n 9 F      SMI     Yes          Aakrati\n10 M      SMI     Yes          Aakrsh \n# ℹ 54 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nvisdat::vis_dat(dad_modified, sort_type = TRUE, palette = \"default\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_modified %>%\n  dplyr::count(gender, college) %>%\n  tt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_r5qk6cc179hf2y5dot02(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_r5qk6cc179hf2y5dot02\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_r5qk6cc179hf2y5dot02(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_r5qk6cc179hf2y5dot02\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '5', j: 0 }, { i: '5', j: 1 }, { i: '5', j: 2 },  ], css_id: 'tinytable_css_ycnhwapmlk65wi6v85z2',}, \n          { positions: [ { i: '0', j: 0 }, { i: '0', j: 1 }, { i: '0', j: 2 },  ], css_id: 'tinytable_css_4zoosicudw80ibwglniu',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_r5qk6cc179hf2y5dot02(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_ycnhwapmlk65wi6v85z2, .table th.tinytable_css_ycnhwapmlk65wi6v85z2 { border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_4zoosicudw80ibwglniu, .table th.tinytable_css_4zoosicudw80ibwglniu { border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_r5qk6cc179hf2y5dot02\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\">gender</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">college</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">n</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">F</td>\n                  <td data-row=\"1\" data-col=\"1\">MIT</td>\n                  <td data-row=\"1\" data-col=\"2\">16</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">F</td>\n                  <td data-row=\"2\" data-col=\"1\">SMI</td>\n                  <td data-row=\"2\" data-col=\"2\">16</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">M</td>\n                  <td data-row=\"3\" data-col=\"1\">MIT</td>\n                  <td data-row=\"3\" data-col=\"2\">16</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">M</td>\n                  <td data-row=\"4\" data-col=\"1\">SMI</td>\n                  <td data-row=\"4\" data-col=\"2\">15</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">NB</td>\n                  <td data-row=\"5\" data-col=\"1\">MIT</td>\n                  <td data-row=\"5\" data-col=\"2\">1</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_modified <- dad %>%\n  dplyr::mutate(across(where(is.character), as.factor))\nglimpse(dad_modified)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 65\nColumns: 4\n$ gender       <fct> F, F, M, F, M, M, M, M, F, M, F, M, F, F, M, M, F, M, M, …\n$ college      <fct> SMI, SMI, SMI, SMI, MIT, MIT, MIT, SMI, SMI, SMI, SMI, SM…\n$ is_dad_weird <fct> No, No, No, Yes, No, No, No, No, Yes, Yes, Yes, Yes, No, …\n$ name         <fct> Manya, Sradha, Arun, Nidhi, Shaurya, Pratham, Jeevan, Dhr…\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_modified %>%\n  stats::setNames(c(\"Gender\", \"College\", \"Is_Your_Dad_Weird\",\"Name\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 65 × 4\n   Gender College Is_Your_Dad_Weird Name   \n   <fct>  <fct>   <fct>             <fct>  \n 1 F      SMI     No                Manya  \n 2 F      SMI     No                Sradha \n 3 M      SMI     No                Arun   \n 4 F      SMI     Yes               Nidhi  \n 5 M      MIT     No                Shaurya\n 6 M      MIT     No                Pratham\n 7 M      MIT     No                Jeevan \n 8 M      SMI     No                Dhruv  \n 9 F      SMI     Yes               Aakrati\n10 M      SMI     Yes               Aakrsh \n# ℹ 55 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\ndad_modified %>%\n  DT::datatable(\n    style = \"default\",\n    caption = htmltools::tags$caption(\n      style = \"caption-side: top; text-align: left; color: black; font-size: 100%;\", \"Weird Dads Dataset (Clean)\"\n    ),\n    options = list(pageLength = 10, autoWidth = TRUE)\n  ) %>%\n  DT::formatStyle(\n    columns = names(dad_modified),\n    fontFamily = \"Roboto Condensed\",\n    fontSize = \"12px\",\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-8d4d29f8af81017583ce\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-8d4d29f8af81017583ce\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption style=\\\"caption-side: top; text-align: left; color: black; font-size: 100%;\\\">Weird Dads Dataset (Clean)<\\/caption>\",\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\"],[\"F\",\"F\",\"M\",\"F\",\"M\",\"M\",\"M\",\"M\",\"F\",\"M\",\"F\",\"M\",\"F\",\"F\",\"M\",\"M\",\"F\",\"M\",\"M\",\"M\",\"M\",\"M\",\"M\",\"F\",\"M\",\"M\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"M\",\"F\",\"F\",\"M\",\"M\",\"M\",\"M\",\"M\",\"NB\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"M\",\"F\",\"M\",\"F\",\"M\",\"F\",\"F\",\"F\",\"M\",\"M\",\"M\",\"M\",\"F\",\"M\",\"M\",\"F\"],[\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"MIT\",\"MIT\",\"MIT\",\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"MIT\",\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"SMI\",\"MIT\",\"MIT\",\"SMI\",\"MIT\",\"MIT\"],[\"No\",\"No\",\"No\",\"Yes\",\"No\",\"No\",\"No\",\"No\",\"Yes\",\"Yes\",\"Yes\",\"Yes\",\"No\",\"No\",\"No\",\"No\",\"No\",\"No\",null,\"No\",\"No\",\"No\",\"No\",\"Yes\",\"No\",\"No\",\"No\",\"No\",\"No\",\"No\",\"No\",\"No\",\"No\",\"No\",\"No\",\"No\",\"No\",\"No\",\"Yes\",\"Yes\",\"No\",\"Yes\",\"Yes\",\"No\",\"No\",\"No\",\"No\",\"Yes\",\"Yes\",\"Yes\",\"No\",\"No\",\"No\",\"No\",\"No\",\"Yes\",\"No\",\"No\",\"Yes\",\"No\",\"No\",\"No\",\"No\",\"Yes\",\"Yes\"],[\"Manya\",\"Sradha\",\"Arun\",\"Nidhi\",\"Shaurya\",\"Pratham\",\"Jeevan\",\"Dhruv\",\"Aakrati\",\"Aakrsh\",\"Kshirav\",\"Aaron\",\"Vagmi\",\"Anushka\",\"Arnav\",\"Harshad\",\"Bhavana\",\"Sumeru\",\"Anonymous\",\"Vinamrah\",\"Neel\",\"Sanihith\",\"Jayden\",\"Harshitha\",\"Rithesh\",\"Arjun\",\"Khushi\",\"Niharika\",\"Teertha\",\"Chitra\",\"Jahanvi\",\"Khanna\",\"Ayanna\",\"Mridul\",\"Yakinya\",\"Ananya\",\"Aadil\",\"Shiva\",\"Aaditya\",\"Rahul\",\"Akshat\",\"Shreya\",\"Payal\",\"Manasvi\",\"Shadeeksha\",\"Purvi\",\"Vedika\",\"Aashna\",\"Shubhangini\",\"Nirmay\",\"Riya\",\"Arun\",\"Avanthika\",\"Nitheesh\",\"Lakshitha\",\"Bhadra\",\"Savanna\",\"Kaiser\",\"Anay\",\"Neel\",\"Amogh\",\"Nandini\",\"Susheel\",\"Garvit\",\"Sri Lakshmi\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>gender<\\/th>\\n      <th>college<\\/th>\\n      <th>is_dad_weird<\\/th>\\n      <th>name<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":10,\"autoWidth\":true,\"columnDefs\":[{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"gender\",\"targets\":1},{\"name\":\"college\",\"targets\":2},{\"name\":\"is_dad_weird\",\"targets\":3},{\"name\":\"name\",\"targets\":4}],\"order\":[],\"orderClasses\":false,\"rowCallback\":\"function(row, data, displayNum, displayIndex, dataIndex) {\\nvar value=data[1]; $(this.api().cell(row, 1).node()).css({'font-family':'Roboto Condensed','font-size':'12px'});\\nvar value=data[2]; $(this.api().cell(row, 2).node()).css({'font-family':'Roboto Condensed','font-size':'12px'});\\nvar value=data[3]; $(this.api().cell(row, 3).node()).css({'font-family':'Roboto Condensed','font-size':'12px'});\\nvar value=data[4]; $(this.api().cell(row, 4).node()).css({'font-family':'Roboto Condensed','font-size':'12px'});\\n}\"}},\"evals\":[\"options.rowCallback\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n## 4. *Data Dictionary*\n\n### *Qualitative Data*\n\n1.  gender(fct): Gender of student (M/F/NB)\n2.  college(fct): Which college the student is from (SMI/MIT)\n3.  is_dad_weird(fct): If the student thinks their dad is weird (Yes/No)\n4.  name(fct): Name of the student\n\n# 5. *Graphs*\n\n## 1. Are SMI dads weirder than MIT dads?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvcd::structable(data = dad_modified, is_dad_weird ~ college) %>% \n  as.matrix() %>%  \n  addmargins()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       is_dad_weird\ncollege No Yes Sum\n    MIT 28   5  33\n    SMI 19  12  31\n    Sum 47  17  64\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nvcd::structable(is_dad_weird ~ college, data = dad_modified) %>%\n    vcd::mosaic(gp = shading_max,\n                main = \"Are SMI dads weirder than MIT dads?\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n### Inferences\n\nOnly a few MIT students find their dads weird, than expected. But, more SMI students find their dads weird, than expected. In both cases, students are more likely to find their dads normal. Also, we can conclude that according to this sample, SMI dads are weirder than MIT dads.\n\n## 2. Irrespective of the college, which gender is more likely to find their dads weird?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_modified %>% \n  gf_bar(~ is_dad_weird | gender,\n         fill = ~gender) %>% \n  gf_labs( title = \"Irrespective of the college, which gender is more likely to find their dads weird?\",\n           x = \"Is Your Dad Weird?\",\n           y = \"Count\") %>% \n  gf_refine(scale_fill_brewer(palette = \"Paired\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n### Inferences\n\nIn general, it is more likely that women find their dads weird than men. This could be because some girl dads can come off as overprotective or 'embarrassing'. The only non-binary student from MIT also finds their dad weird. Perhaps their father is not as supportive as they'd like.\n\n## 3. Are women more likely to find their dads weird than men?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_modified2 <- dad_modified %>%\n  filter(gender != \"NB\")\n\ndad_modified2 %>% \n  gf_bar(~ gender | college,\n         fill = ~ is_dad_weird,\n         position = \"fill\") %>%\n  gf_labs(\n    title = \"Are women more likely to find their dads weird than men?\",\n    x = \"Gender\",\n    y = \"Proportion\",\n    fill = \"Legend: Is Your Dad Weird?\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n### Inferences\n\nIn the mosaic graph, we could only infer that SMI dads are weirder than MIT dads, but here we can also talk about it with respect to gender. In SMI, boys are more likely to find their dads weird, and in MIT, girls are more likely to find their dads weird.\n\nThis reason behind this could be that some dads are not very supportive when it comes to sending their son to a design school and would rather have them do engineering. Because of clashes with their dads, maybe SMI boys find their dads weird. Same goes for MIT girls who took up engineering.\n\n## 4. Are students more likely to think their dads are weird?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_modified %>% \n  gf_bar(~ is_dad_weird, fill = ~ is_dad_weird) %>% \n  gf_labs( title = \"Are students more likely to think their dads are weird?\",\n           x = \"Is Your Dad Weird?\",\n           y = \"Count\",\n           fill = \"Legend: Is Your Dad Weird?\") %>% \n  gf_refine(scale_fill_brewer(palette = \"Accent\", direction =-1))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\n### Inferences\n\nOverall, students are more likely to find their dads normal.\n\n## 6. *Summary of Inferences*\n\nOverall, most students across both colleges find their dads normal. However, based on this sample, SMI students are slightly more likely to find their dads weird than MIT students. When looking at gender, MIT girls appear more likely to perceive their dads as weird, while in SMI, boys show this trend more. These differences may reflect family expectations, academic choices, and communication dynamics rather than universal patterns.\n\n## 7. *Surprising Aspects*\n\nI thought MIT dads would be weirder than SMI dads because I assumed that dads who allow their children to study in a design school would be fun, easy-going and open-minded and would not be considered weird by their children. Results could change if a different sample was taken, perhaps after exam results are released.\n\n## 8. *Pearson's Chi-squared test- Inference test for two proportions*\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontingency_table <- vcd::structable(data = dad_modified, is_dad_weird ~ college) %>% \n  as.matrix() %>%  \n  addmargins()\n\nxq_test_object <- xchisq.test(contingency_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  x\nX-squared = 4.5477, df = 4, p-value = 0.3369\n\n 28.00     5.00    33.00  \n(24.23)  ( 8.77)  (33.00) \n [0.59]   [1.62]   [0.00] \n< 0.76>  <-1.27>  < 0.00> \n     \n 19.00    12.00    31.00  \n(22.77)  ( 8.23)  (31.00) \n [0.62]   [1.72]   [0.00] \n<-0.79>  < 1.31>  < 0.00> \n     \n 47.00    17.00    64.00  \n(47.00)  (17.00)  (64.00) \n [0.00]   [0.00]   [0.00] \n< 0.00>  < 0.00>  < 0.00> \n     \nkey:\n\tobserved\n\t(expected)\n\t[contribution to X-squared]\n\t<Pearson residual>\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nxq_test_object %>%\n  broom::tidy() %>%\n  select(statistic) %>%\n  as.numeric() -> X_squared_observed\nX_squared_observed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.547698\n```\n\n\n:::\n:::\n\n\n\nLet us also evaluate the critical value for the Chi-Square distribution, with alpha = 0.05 and df = (nrows-1)\\*(ncols-1) = 4:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Determine the Chi-Square critical value\nX_squared_critical <- qchisq(\n  p = .05,\n  df = 4, # (nrows-1) * (ncols-1)\n  lower.tail = FALSE\n)\nX_squared_critical\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.487729\n```\n\n\n:::\n:::\n\n\n\nWe see that our observed chi squared value = 4.547698, and the critical value = 9.487729, which is larger. The p-value is 0.3369, which is greater than 0.05, indicating that the NULL hypothesis cannot be rejected. Therefore, we do not have enough evidence to conclude that the proportions of students who find their dads weird differ by college.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/datatables-binding-0.34.0/datatables.js\"></script>\n<script src=\"../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}